config/routes.rb
Rails.application.routes.draw do
  get "signup" => "users#signup", :as => "signup"
  get "login" => "users#login", :as => "login"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'page#welcome'
  get '/about' => 'page#about'
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  resources :users, only: [:create]
  resources :comments, only: [:create]
  resources :issues

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :issue
	belongs_to :user
end

app/models/issue.rb
class Issue < ActiveRecord::Base 
	has_many :comments, dependent: :destroy
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	# 自带验证密码
	has_secure_password
	has_many :comments
	has_many :issues

	before_create { generate_token(:auth_token)}
	validates :name, :email, presence: true
	validates :name, :email, uniqueness: {case_sensitive: false}

	mount_uploader :avatar, AvatarUploader
	


	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def current_user
  	@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end


  # The method helper_method is to explicitly share some methods defined in the controller 
  # to make them available for the view.
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	  @comment = Comment.new(comment_params)
	  @comment.save
	  respond_to do |format|
	  	format.js	
	  end
	end
	private
		def comment_params
			params.require(:comment).permit(:issue_id, :user_id, :content)
		end
 end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
  	@issue = Issue.find(params[:id])
    @comments = @issue.comments
  end

  def destroy
  	i = Issue.find(params[:id])
  	i.destroy
  	redirect_to :root
  end

  def new
    if not current_user
      flash[:notice] = "登录后才可以发布😯"
      redirect_to :root
      return
    else
      @issue = Issue.new
    end
  end

  def create
  	issue = Issue.new issue_params
    issue.user_id = current_user.id
    issue.save
  	redirect_to :root
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
  	i = Issue.find(params[:id])
  	i.update_attributes(issue_params)
  	redirect_to :root
  end

  private
  	def issue_params
  		params.require(:issue).permit(:title, :content, :user_id)
  	end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
 def welcome
 	@issues = Issue.all.reverse
 end

 def about
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      cookies[:auth_token] = @user.auth_token
    	redirect_to :root
    else
      render :signup
    end
  end

  def create_login_session
  	user = User.find_by_name(params[:name])
  	# has_secure_password
  	if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      flash.notice = '登录成功'
  		redirect_to :root
  	else
      flash.notice = '用户名密码错误'
  		redirect_to :login
  	end
  end

  def logout
  	cookies.delete(:auth_token)
  	redirect_to :root
  end

  private
  def user_params
  	# 虽然密码的字段是password_digest
  	# params.require(:user).permit(:name,:password,:email, :auth_token)
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
		    no_intra_emphasis: true,
		    fenced_code_blocks: true,
		    lax_html_blocks: true,
		    strikethrough: true,
		    superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(text).html_safe
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$('.replies').append("<%= j render partial: 'shared/comment', locals: {c: @comment} %>") 
$(".reply textarea").val('');

app/views/issues/_form.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/edit.html.erb
<%= render partial: 'form'%>

app/views/issues/new.html.erb
<%= render partial: 'form' %>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>
    <% if current_user && current_user == @issue.user %>
      <%= link_to 'Destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %> 
      <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
        <img src=<%= @issue.user.avatar %> alt="" class="image-circle">
      </div>
      <div class="body">
        <div class="heading">
          <h5 class="name"><a href="#"><%=  @issue.user.name %></a></h5>
        </div>
        <%= markdown @issue.content %>
      </div>
    </article>
    <% @comments.each do |c| %>
      <%= render partial: 'shared/comment', locals: {c: c} %>
    <% end %>
  </div>
  <% if current_user %>
    <%= render partial: 'shared/comment_box'  %>
  <% else %>
    <%= link_to '登录后才可以评论哦', login_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>meetup</title>
  <%= stylesheet_link_tag "application"%>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
  <script>
  $('.home-banner').anystretch();
 var hideNotice = function(){
     $(".notice").fadeOut("slow");
 }
 setTimeout(hideNotice, 4000);
</script>

</head>
<body class="<%= params[:controller]+ '-' + params[:action] %>">
  <div class="navbar clearfix">
    <div class="container">
      <a class="navbar-brand" href="/"> 
        Meetup
      </a>
      <ul class="nav left">
        <li><a href="/about.html">About</a></li>
        <!-- <li><a href="#">placeholder</a></li> -->
      </ul>
      <ul class="nav right">
        <% if current_user %>
          <li><img src=<%= current_user.avatar %> alt="" class="image-circle"></li>
          <li><%= link_to "logout", logout_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to "login", login_path %></li>
          <li><%= link_to "signup", signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% if flash.notice %>
    <div class="notice">
      <%= flash.notice %>
    </div>
  <% end %>
  <%= yield %>
  <div class="footer">
    <div class="container">
      <!--  -->
    </div>
  </div>
  <script>
    $('.home-banner').anystretch();
  </script>
</body>

</html>

app/views/page/_issue_list.html.erb
<div class="container clearfix">
  <div class="issue-list">
    <% @issues.each do |i| %>
    <article class="issue clearfix">
      <div class="avatar">
        <a href="/">
          <img src=<%= i.user.avatar %> alt="" class="image-circle">
</a>      </div>
      <div class="body">
        <h5 class="title">
          <%= link_to i.title ,issue_path(i) %>
        </h5>
        <a class="read-more" href="#">read</a>
        <span class="meta-data">
          <a href="/"> <%=i.user.name%> </a>
          <%= time_ago_in_words(i.created_at) %> ago
            
        </span>
      </div>
      <div class="issue-comment-count">
        <i class="fa fa-comments fa-2x icon-muted"></i>
        <%= link_to i.comments.count,  i%>
      </div>
    </article>
  <% end %>
  </div>
</div>

app/views/page/about.html.erb
<div class="container">
  这是一个聚会活动发布的小网站，如果喜欢请注册进来玩玩～
</div>

app/views/page/welcome.html.erb
<div class="home-banner" data-stretch="<%= image_url "whitey.png" %>">
	<div class="banner-inner container clearfix">
		<h1> Welcome!</h1>
		<p class="subheading">最重要是开心嘛</p>
		<div class="home-banner-links">
			<%= link_to "发布新活动", "/issues/new",class: "banner-btn btn" %>
		</div>
	</div>
</div>
  <%= render partial: 'issue_list' %>
<script>
  $('.home-banner').anystretch();
</script>

app/views/shared/_comment.html.erb
    <div class="reply clearfix">
       <div class="avatar">
         <img src=<%= c.user.avatar %> alt="" class="image-circle">
       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.user.name, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> ago
            </span>
         </div>
         <%= markdown c.content %>
       </div>
    </div>

app/views/shared/_comment_box.html.erb
<article class="reply clearfix">
  <div class="avatar">
      <img src=<%= current_user.avatar %> alt="" class="image-circle">  </div>
  <div class="body">
  <%= form_for(Comment.new(:issue_id => @issue.id, :user_id => current_user.id), remote: true) do |f|  %>
    <%= f.text_area(:content) %>
    <%= f.hidden_field :issue_id %>
    <%= f.hidden_field :user_id  %>
    <%= submit_tag '提交评论', class: 'btn btn-primary btn-submit' %>
  <% end %>
  </div>
</article>

<script>
  var commenter_list = [];
  $('.reply .name a').each( function() {
    if($.inArray($(this).text(), commenter_list) < 0 ){
      commenter_list.push($(this).text());
    }
  });
  $('textarea').atwho({at: "@", 'data':commenter_list});
</script>

app/views/shared/_comment_list.html.erb
<% @comments.each do |c| %>
    <div class="reply clearfix">
       <div class="avatar">
         <img src=<%= c.user.avatar %> alt="" class="image-circle">
       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.user.name, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> ago
            </span>
         </div>
         <%= c.content %>
       </div>
    </div>
<% end %>

app/views/users/login.html.erb
<div class="login-form-container clearfix">
  <div class="login-form">
    <%= form_tag "/create_login_session" do %>
    <dl class="form">
      <dt>
        <%= label_tag "用户名" %>
      </dt>
      <dd>
        <%= text_field_tag :name, params[:name] %>
      </dd>
    </dl>
    <dl class="form">
      <dt>
        <%= label_tag "密码" %>
      </dt>
      <dd>
        <%= password_field_tag :password, params[:password] %>
      </dd>
    </dl>
    <dl class="form remember-me">
      <%= check_box_tag :remember_me, 1, params[:remember_me] %>
      <%= label_tag :remember_me %>
    </dl>
    <p> <%= submit_tag "登录", :class => "login-button btn btn-primary" %> </p>
    <div class="need-signup">
      <%= link_to "没有账号？注册一个吧", signup_path %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<div class="signup-form-container clearfix">
  <div class="signup-form">
    <%= form_for @user do |f| %>

        <dl class="form">
          <dt><%= f.label :avatar, "上传个头像吧" %></dt>
          <dd style="border: 1px solid"><%= f.file_field :avatar %></dd>
        </dl>

        <dl class="form">
          <dt><%= f.label :name, "用户名" %></dt>
          <dd><%= f.text_field :name %></dd>
          <% if @user.errors[:name].any? %>
            <dd class="error"><%= @user.errors[:name][0] %></dd>
          <%end %>
        </dl>
        <dl class="form">
          <dt><%= f.label :email %></dt>
          <dd><%= f.text_field :email %></dd>
          <% if @user.errors[:email].any? %>
            <dd class="error"><%= @user.errors[:email][0] %></dd>
          <%end %>
        </dl>
        <dl class="form">
          <dt><%= f.label :password, "密码" %></dt>
          <dd><%= f.password_field :password %></dd>
          <% if @user.errors[:password].any? %>
            <dd class="error"><%= @user.errors[:password][0] %></dd>
          <%end %>
        </dl>
        <dl class="form">
          <dt><%= f.label :password_confirmation, "请再输入一次" %></dt>
          <dd><%= f.password_field :password_confirmation %></dd>
          <% if @user.errors[:password_confirmation].any? %>
            <dd class="error"><%= @user.errors[:password_confirmation][0] %></dd>
          <%end %>
        </dl>
        <p><%= f.submit "注册", :class => "signup-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

<!-- http://happypeter.github.io/rails-tricks/01_signup.html -->